### ISSUE TITLE
Render pending publish rss page

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx#213]
##Overview
If https://legacy.cnx.org/pending.rss could show the rendered page again instead of just the markup:
<img width="822" alt="screen shot 2018-12-20 at 9 33 57 am" src="https://user-images.githubusercontent.com/1895432/50293969-6c1d8900-043a-11e9-82c4-63b8c43ca8f7.png">

Makes the page more immediately legible; nice to have.
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
The rss page will show text and style instead of markup.
## Acceptance Criteria
The rss page will show text and style instead of markup.

**Comment by Bkblodget** [comment]
If you look at this in firefox it will render as text

**Comment by oscryan** [comment]
The screenshot is from firefox

**Comment by Bkblodget** [comment]
RSS Subscription extension (by google) - chrome app. Still needs to be tested for approval

**Comment by omehes** [comment]
This is how it looks in rss reader chrome extension:

![rss1](https://user-images.githubusercontent.com/44207656/51927217-b50d1980-23b8-11e9-861f-3e855bfac122.png)

**Comment by oscryan** [comment]
So I have to look at it in an extension and I can't just go to https://legacy.cnx.org/pending.rss ?

**Comment by Bkblodget** [comment]
Most browsers require an extension to few the RSS feed (screenshots below). Because these browsers offer an extension for rss rendering, it frees up the burden on devs to create a reader for us. 

![screen shot 2019-01-29 at 12 56 58 pm](https://user-images.githubusercontent.com/11299035/51933307-9f9eec00-23c6-11e9-83ac-e2c11a8198f2.png)
![screen shot 2019-01-29 at 12 57 19 pm](https://user-images.githubusercontent.com/11299035/51933312-a3327300-23c6-11e9-8787-236e81b75cb1.png)
![screen shot 2019-01-29 at 12 57 33 pm](https://user-images.githubusercontent.com/11299035/51933318-a62d6380-23c6-11e9-9725-fcd852324f65.png)
